/**
 * ========================================
 * CATÁLOGOS DEL MINISTERIO DE HACIENDA
 * ========================================
 * Departamentos, municipios y actividades
 * económicas de El Salvador para formularios.
 */

export interface Departamento {
  codigo: string;
  nombre: string;
}

export interface Municipio {
  codigo: string;
  nombre: string;
  departamento: string; // código del departamento padre
}

export interface ActividadEconomica {
  codigo: string;
  descripcion: string;
}

// ── DEPARTAMENTOS DE EL SALVADOR ──────────────
export const DEPARTAMENTOS: Departamento[] = [
  { codigo: '01', nombre: 'Ahuachapán' },
  { codigo: '02', nombre: 'Santa Ana' },
  { codigo: '03', nombre: 'Sonsonate' },
  { codigo: '04', nombre: 'Chalatenango' },
  { codigo: '05', nombre: 'La Libertad' },
  { codigo: '06', nombre: 'San Salvador' },
  { codigo: '07', nombre: 'Cuscatlán' },
  { codigo: '08', nombre: 'La Paz' },
  { codigo: '09', nombre: 'Cabañas' },
  { codigo: '10', nombre: 'San Vicente' },
  { codigo: '11', nombre: 'Usulután' },
  { codigo: '12', nombre: 'San Miguel' },
  { codigo: '13', nombre: 'Morazán' },
  { codigo: '14', nombre: 'La Unión' },
];

// ── MUNICIPIOS POR DEPARTAMENTO ───────────────
// Catálogo oficial MH - se incluyen los principales
export const MUNICIPIOS: Municipio[] = [
  // Ahuachapán (01)
  { codigo: '01', nombre: 'Ahuachapán', departamento: '01' },
  { codigo: '02', nombre: 'Apaneca', departamento: '01' },
  { codigo: '03', nombre: 'Atiquizaya', departamento: '01' },
  { codigo: '04', nombre: 'Concepción de Ataco', departamento: '01' },
  { codigo: '05', nombre: 'El Refugio', departamento: '01' },
  { codigo: '06', nombre: 'Guaymango', departamento: '01' },
  { codigo: '07', nombre: 'Jujutla', departamento: '01' },
  { codigo: '08', nombre: 'San Francisco Menéndez', departamento: '01' },
  { codigo: '09', nombre: 'San Lorenzo', departamento: '01' },
  { codigo: '10', nombre: 'San Pedro Puxtla', departamento: '01' },
  { codigo: '11', nombre: 'Tacuba', departamento: '01' },
  { codigo: '12', nombre: 'Turín', departamento: '01' },

  // Santa Ana (02)
  { codigo: '01', nombre: 'Santa Ana', departamento: '02' },
  { codigo: '02', nombre: 'Candelaria de la Frontera', departamento: '02' },
  { codigo: '03', nombre: 'Chalchuapa', departamento: '02' },
  { codigo: '04', nombre: 'Coatepeque', departamento: '02' },
  { codigo: '05', nombre: 'El Congo', departamento: '02' },
  { codigo: '06', nombre: 'El Porvenir', departamento: '02' },
  { codigo: '07', nombre: 'Masahuat', departamento: '02' },
  { codigo: '08', nombre: 'Metapán', departamento: '02' },
  { codigo: '09', nombre: 'San Antonio Pajonal', departamento: '02' },
  { codigo: '10', nombre: 'San Sebastián Salitrillo', departamento: '02' },
  { codigo: '11', nombre: 'Santa Rosa Guachipilín', departamento: '02' },
  { codigo: '12', nombre: 'Santiago de la Frontera', departamento: '02' },
  { codigo: '13', nombre: 'Texistepeque', departamento: '02' },

  // Sonsonate (03)
  { codigo: '01', nombre: 'Sonsonate', departamento: '03' },
  { codigo: '02', nombre: 'Acajutla', departamento: '03' },
  { codigo: '03', nombre: 'Armenia', departamento: '03' },
  { codigo: '04', nombre: 'Caluco', departamento: '03' },
  { codigo: '05', nombre: 'Cuisnahuat', departamento: '03' },
  { codigo: '06', nombre: 'Izalco', departamento: '03' },
  { codigo: '07', nombre: 'Juayúa', departamento: '03' },
  { codigo: '08', nombre: 'Nahuizalco', departamento: '03' },
  { codigo: '09', nombre: 'Nahulingo', departamento: '03' },
  { codigo: '10', nombre: 'Salcoatitán', departamento: '03' },
  { codigo: '11', nombre: 'San Antonio del Monte', departamento: '03' },
  { codigo: '12', nombre: 'San Julián', departamento: '03' },
  { codigo: '13', nombre: 'Santa Catarina Masahuat', departamento: '03' },
  { codigo: '14', nombre: 'Santa Isabel Ishuatán', departamento: '03' },
  { codigo: '15', nombre: 'Santo Domingo de Guzmán', departamento: '03' },
  { codigo: '16', nombre: 'Sonzacate', departamento: '03' },

  // Chalatenango (04)
  { codigo: '01', nombre: 'Chalatenango', departamento: '04' },
  { codigo: '02', nombre: 'Agua Caliente', departamento: '04' },
  { codigo: '03', nombre: 'Arcatao', departamento: '04' },
  { codigo: '04', nombre: 'Azacualpa', departamento: '04' },
  { codigo: '05', nombre: 'Citalá', departamento: '04' },
  { codigo: '06', nombre: 'Concepción Quezaltepeque', departamento: '04' },
  { codigo: '07', nombre: 'Dulce Nombre de María', departamento: '04' },
  { codigo: '08', nombre: 'El Carrizal', departamento: '04' },
  { codigo: '09', nombre: 'El Paraíso', departamento: '04' },
  { codigo: '10', nombre: 'La Laguna', departamento: '04' },
  { codigo: '11', nombre: 'La Palma', departamento: '04' },
  { codigo: '12', nombre: 'La Reina', departamento: '04' },
  { codigo: '13', nombre: 'Las Vueltas', departamento: '04' },
  { codigo: '14', nombre: 'Nueva Concepción', departamento: '04' },
  { codigo: '15', nombre: 'Nueva Trinidad', departamento: '04' },
  { codigo: '16', nombre: 'Nombre de Jesús', departamento: '04' },
  { codigo: '17', nombre: 'Ojos de Agua', departamento: '04' },
  { codigo: '18', nombre: 'Potonico', departamento: '04' },
  { codigo: '19', nombre: 'San Antonio de la Cruz', departamento: '04' },
  { codigo: '20', nombre: 'San Antonio Los Ranchos', departamento: '04' },
  { codigo: '21', nombre: 'San Fernando', departamento: '04' },
  { codigo: '22', nombre: 'San Francisco Lempa', departamento: '04' },
  { codigo: '23', nombre: 'San Francisco Morazán', departamento: '04' },
  { codigo: '24', nombre: 'San Ignacio', departamento: '04' },
  { codigo: '25', nombre: 'San Isidro Labrador', departamento: '04' },
  { codigo: '26', nombre: 'San Luis del Carmen', departamento: '04' },
  { codigo: '27', nombre: 'San Miguel de Mercedes', departamento: '04' },
  { codigo: '28', nombre: 'San Rafael', departamento: '04' },
  { codigo: '29', nombre: 'Santa Rita', departamento: '04' },
  { codigo: '30', nombre: 'Tejutla', departamento: '04' },

  // La Libertad (05)
  { codigo: '01', nombre: 'Santa Tecla', departamento: '05' },
  { codigo: '02', nombre: 'Antiguo Cuscatlán', departamento: '05' },
  { codigo: '03', nombre: 'Ciudad Arce', departamento: '05' },
  { codigo: '04', nombre: 'Colón', departamento: '05' },
  { codigo: '05', nombre: 'Comasagua', departamento: '05' },
  { codigo: '06', nombre: 'Huizúcar', departamento: '05' },
  { codigo: '07', nombre: 'Jayaque', departamento: '05' },
  { codigo: '08', nombre: 'Jicalapa', departamento: '05' },
  { codigo: '09', nombre: 'La Libertad', departamento: '05' },
  { codigo: '10', nombre: 'Nuevo Cuscatlán', departamento: '05' },
  { codigo: '11', nombre: 'Opico', departamento: '05' },
  { codigo: '12', nombre: 'Quezaltepeque', departamento: '05' },
  { codigo: '13', nombre: 'Sacacoyo', departamento: '05' },
  { codigo: '14', nombre: 'San José Villanueva', departamento: '05' },
  { codigo: '15', nombre: 'San Juan Opico', departamento: '05' },
  { codigo: '16', nombre: 'San Matías', departamento: '05' },
  { codigo: '17', nombre: 'San Pablo Tacachico', departamento: '05' },
  { codigo: '18', nombre: 'Talnique', departamento: '05' },
  { codigo: '19', nombre: 'Tamanique', departamento: '05' },
  { codigo: '20', nombre: 'Teotepeque', departamento: '05' },
  { codigo: '21', nombre: 'Tepecoyo', departamento: '05' },
  { codigo: '22', nombre: 'Zaragoza', departamento: '05' },

  // San Salvador (06)
  { codigo: '01', nombre: 'San Salvador', departamento: '06' },
  { codigo: '02', nombre: 'Aguilares', departamento: '06' },
  { codigo: '03', nombre: 'Apopa', departamento: '06' },
  { codigo: '04', nombre: 'Ayutuxtepeque', departamento: '06' },
  { codigo: '05', nombre: 'Cuscatancingo', departamento: '06' },
  { codigo: '06', nombre: 'Delgado', departamento: '06' },
  { codigo: '07', nombre: 'El Paisnal', departamento: '06' },
  { codigo: '08', nombre: 'Guazapa', departamento: '06' },
  { codigo: '09', nombre: 'Ilopango', departamento: '06' },
  { codigo: '10', nombre: 'Mejicanos', departamento: '06' },
  { codigo: '11', nombre: 'Nejapa', departamento: '06' },
  { codigo: '12', nombre: 'Panchimalco', departamento: '06' },
  { codigo: '13', nombre: 'Rosario de Mora', departamento: '06' },
  { codigo: '14', nombre: 'San Marcos', departamento: '06' },
  { codigo: '15', nombre: 'San Martín', departamento: '06' },
  { codigo: '16', nombre: 'Santiago Texacuangos', departamento: '06' },
  { codigo: '17', nombre: 'Santo Tomás', departamento: '06' },
  { codigo: '18', nombre: 'Soyapango', departamento: '06' },
  { codigo: '19', nombre: 'Tonacatepeque', departamento: '06' },

  // Cuscatlán (07)
  { codigo: '01', nombre: 'Cojutepeque', departamento: '07' },
  { codigo: '02', nombre: 'Candelaria', departamento: '07' },
  { codigo: '03', nombre: 'El Carmen', departamento: '07' },
  { codigo: '04', nombre: 'El Rosario', departamento: '07' },
  { codigo: '05', nombre: 'Monte San Juan', departamento: '07' },
  { codigo: '06', nombre: 'Oratorio de Concepción', departamento: '07' },
  { codigo: '07', nombre: 'San Bartolomé Perulapía', departamento: '07' },
  { codigo: '08', nombre: 'San Cristóbal', departamento: '07' },
  { codigo: '09', nombre: 'San José Guayabal', departamento: '07' },
  { codigo: '10', nombre: 'San Pedro Perulapán', departamento: '07' },
  { codigo: '11', nombre: 'San Rafael Cedros', departamento: '07' },
  { codigo: '12', nombre: 'San Ramón', departamento: '07' },
  { codigo: '13', nombre: 'Santa Cruz Analquito', departamento: '07' },
  { codigo: '14', nombre: 'Santa Cruz Michapa', departamento: '07' },
  { codigo: '15', nombre: 'Suchitoto', departamento: '07' },
  { codigo: '16', nombre: 'Tenancingo', departamento: '07' },

  // La Paz (08)
  { codigo: '01', nombre: 'Zacatecoluca', departamento: '08' },
  { codigo: '02', nombre: 'Cuyultitán', departamento: '08' },
  { codigo: '03', nombre: 'El Rosario', departamento: '08' },
  { codigo: '04', nombre: 'Jerusalén', departamento: '08' },
  { codigo: '05', nombre: 'Mercedes La Ceiba', departamento: '08' },
  { codigo: '06', nombre: 'Olocuilta', departamento: '08' },
  { codigo: '07', nombre: 'Paraíso de Osorio', departamento: '08' },
  { codigo: '08', nombre: 'San Antonio Masahuat', departamento: '08' },
  { codigo: '09', nombre: 'San Emigdio', departamento: '08' },
  { codigo: '10', nombre: 'San Francisco Chinameca', departamento: '08' },
  { codigo: '11', nombre: 'San Juan Nonualco', departamento: '08' },
  { codigo: '12', nombre: 'San Juan Talpa', departamento: '08' },
  { codigo: '13', nombre: 'San Juan Tepezontes', departamento: '08' },
  { codigo: '14', nombre: 'San Luis Talpa', departamento: '08' },
  { codigo: '15', nombre: 'San Miguel Tepezontes', departamento: '08' },
  { codigo: '16', nombre: 'San Pedro Masahuat', departamento: '08' },
  { codigo: '17', nombre: 'San Pedro Nonualco', departamento: '08' },
  { codigo: '18', nombre: 'San Rafael Obrajuelo', departamento: '08' },
  { codigo: '19', nombre: 'Santa María Ostuma', departamento: '08' },
  { codigo: '20', nombre: 'Santiago Nonualco', departamento: '08' },
  { codigo: '21', nombre: 'Tapalhuaca', departamento: '08' },
  { codigo: '22', nombre: 'San Luis La Herradura', departamento: '08' },

  // Cabañas (09)
  { codigo: '01', nombre: 'Sensuntepeque', departamento: '09' },
  { codigo: '02', nombre: 'Cinquera', departamento: '09' },
  { codigo: '03', nombre: 'Dolores', departamento: '09' },
  { codigo: '04', nombre: 'Guacotecti', departamento: '09' },
  { codigo: '05', nombre: 'Ilobasco', departamento: '09' },
  { codigo: '06', nombre: 'Jutiapa', departamento: '09' },
  { codigo: '07', nombre: 'San Isidro', departamento: '09' },
  { codigo: '08', nombre: 'Tejutepeque', departamento: '09' },
  { codigo: '09', nombre: 'Victoria', departamento: '09' },

  // San Vicente (10)
  { codigo: '01', nombre: 'San Vicente', departamento: '10' },
  { codigo: '02', nombre: 'Apastepeque', departamento: '10' },
  { codigo: '03', nombre: 'Guadalupe', departamento: '10' },
  { codigo: '04', nombre: 'San Cayetano Istepeque', departamento: '10' },
  { codigo: '05', nombre: 'San Esteban Catarina', departamento: '10' },
  { codigo: '06', nombre: 'San Ildefonso', departamento: '10' },
  { codigo: '07', nombre: 'San Lorenzo', departamento: '10' },
  { codigo: '08', nombre: 'San Sebastián', departamento: '10' },
  { codigo: '09', nombre: 'Santa Clara', departamento: '10' },
  { codigo: '10', nombre: 'Santo Domingo', departamento: '10' },
  { codigo: '11', nombre: 'Tecoluca', departamento: '10' },
  { codigo: '12', nombre: 'Tepetitán', departamento: '10' },
  { codigo: '13', nombre: 'Verapaz', departamento: '10' },

  // Usulután (11)
  { codigo: '01', nombre: 'Usulután', departamento: '11' },
  { codigo: '02', nombre: 'Alegría', departamento: '11' },
  { codigo: '03', nombre: 'Berlín', departamento: '11' },
  { codigo: '04', nombre: 'California', departamento: '11' },
  { codigo: '05', nombre: 'Concepción Batres', departamento: '11' },
  { codigo: '06', nombre: 'El Triunfo', departamento: '11' },
  { codigo: '07', nombre: 'Ereguayquín', departamento: '11' },
  { codigo: '08', nombre: 'Estanzuelas', departamento: '11' },
  { codigo: '09', nombre: 'Jiquilisco', departamento: '11' },
  { codigo: '10', nombre: 'Jucuapa', departamento: '11' },
  { codigo: '11', nombre: 'Jucuarán', departamento: '11' },
  { codigo: '12', nombre: 'Mercedes Umaña', departamento: '11' },
  { codigo: '13', nombre: 'Nueva Granada', departamento: '11' },
  { codigo: '14', nombre: 'Ozatlán', departamento: '11' },
  { codigo: '15', nombre: 'Puerto El Triunfo', departamento: '11' },
  { codigo: '16', nombre: 'San Agustín', departamento: '11' },
  { codigo: '17', nombre: 'San Buenaventura', departamento: '11' },
  { codigo: '18', nombre: 'San Dionisio', departamento: '11' },
  { codigo: '19', nombre: 'San Francisco Javier', departamento: '11' },
  { codigo: '20', nombre: 'Santa Elena', departamento: '11' },
  { codigo: '21', nombre: 'Santa María', departamento: '11' },
  { codigo: '22', nombre: 'Santiago de María', departamento: '11' },
  { codigo: '23', nombre: 'Tecapán', departamento: '11' },

  // San Miguel (12)
  { codigo: '01', nombre: 'San Miguel', departamento: '12' },
  { codigo: '02', nombre: 'Carolina', departamento: '12' },
  { codigo: '03', nombre: 'Chapeltique', departamento: '12' },
  { codigo: '04', nombre: 'Chinameca', departamento: '12' },
  { codigo: '05', nombre: 'Chirilagua', departamento: '12' },
  { codigo: '06', nombre: 'Ciudad Barrios', departamento: '12' },
  { codigo: '07', nombre: 'Comacarán', departamento: '12' },
  { codigo: '08', nombre: 'El Tránsito', departamento: '12' },
  { codigo: '09', nombre: 'Lolotique', departamento: '12' },
  { codigo: '10', nombre: 'Moncagua', departamento: '12' },
  { codigo: '11', nombre: 'Nueva Guadalupe', departamento: '12' },
  { codigo: '12', nombre: 'Nuevo Edén de San Juan', departamento: '12' },
  { codigo: '13', nombre: 'Quelepa', departamento: '12' },
  { codigo: '14', nombre: 'San Antonio', departamento: '12' },
  { codigo: '15', nombre: 'San Gerardo', departamento: '12' },
  { codigo: '16', nombre: 'San Jorge', departamento: '12' },
  { codigo: '17', nombre: 'San Luis de la Reina', departamento: '12' },
  { codigo: '18', nombre: 'San Rafael Oriente', departamento: '12' },
  { codigo: '19', nombre: 'Sesori', departamento: '12' },
  { codigo: '20', nombre: 'Uluazapa', departamento: '12' },

  // Morazán (13)
  { codigo: '01', nombre: 'San Francisco Gotera', departamento: '13' },
  { codigo: '02', nombre: 'Arambala', departamento: '13' },
  { codigo: '03', nombre: 'Cacaopera', departamento: '13' },
  { codigo: '04', nombre: 'Chilanga', departamento: '13' },
  { codigo: '05', nombre: 'Corinto', departamento: '13' },
  { codigo: '06', nombre: 'Delicias de Concepción', departamento: '13' },
  { codigo: '07', nombre: 'El Divisadero', departamento: '13' },
  { codigo: '08', nombre: 'El Rosario', departamento: '13' },
  { codigo: '09', nombre: 'Gualococti', departamento: '13' },
  { codigo: '10', nombre: 'Guatajiagua', departamento: '13' },
  { codigo: '11', nombre: 'Joateca', departamento: '13' },
  { codigo: '12', nombre: 'Jocoaitique', departamento: '13' },
  { codigo: '13', nombre: 'Jocoro', departamento: '13' },
  { codigo: '14', nombre: 'Lolotiquillo', departamento: '13' },
  { codigo: '15', nombre: 'Meanguera', departamento: '13' },
  { codigo: '16', nombre: 'Osicala', departamento: '13' },
  { codigo: '17', nombre: 'Perquín', departamento: '13' },
  { codigo: '18', nombre: 'San Carlos', departamento: '13' },
  { codigo: '19', nombre: 'San Fernando', departamento: '13' },
  { codigo: '20', nombre: 'San Isidro', departamento: '13' },
  { codigo: '21', nombre: 'San Simón', departamento: '13' },
  { codigo: '22', nombre: 'Sensembra', departamento: '13' },
  { codigo: '23', nombre: 'Sociedad', departamento: '13' },
  { codigo: '24', nombre: 'Torola', departamento: '13' },
  { codigo: '25', nombre: 'Yamabal', departamento: '13' },
  { codigo: '26', nombre: 'Yoloaiquín', departamento: '13' },

  // La Unión (14)
  { codigo: '01', nombre: 'La Unión', departamento: '14' },
  { codigo: '02', nombre: 'Anamorós', departamento: '14' },
  { codigo: '03', nombre: 'Bolívar', departamento: '14' },
  { codigo: '04', nombre: 'Concepción de Oriente', departamento: '14' },
  { codigo: '05', nombre: 'Conchagua', departamento: '14' },
  { codigo: '06', nombre: 'El Carmen', departamento: '14' },
  { codigo: '07', nombre: 'El Sauce', departamento: '14' },
  { codigo: '08', nombre: 'Intipucá', departamento: '14' },
  { codigo: '09', nombre: 'Lislique', departamento: '14' },
  { codigo: '10', nombre: 'Meanguera del Golfo', departamento: '14' },
  { codigo: '11', nombre: 'Nueva Esparta', departamento: '14' },
  { codigo: '12', nombre: 'Pasaquina', departamento: '14' },
  { codigo: '13', nombre: 'Polorós', departamento: '14' },
  { codigo: '14', nombre: 'San Alejo', departamento: '14' },
  { codigo: '15', nombre: 'San José', departamento: '14' },
  { codigo: '16', nombre: 'Santa Rosa de Lima', departamento: '14' },
  { codigo: '17', nombre: 'Yayantique', departamento: '14' },
  { codigo: '18', nombre: 'Yucuaiquín', departamento: '14' },
];

/**
 * Retorna los municipios filtrados por departamento
 */
export function getMunicipiosPorDepto(codigoDepto: string): Municipio[] {
  return MUNICIPIOS.filter((m) => m.departamento === codigoDepto);
}

// ── ACTIVIDADES ECONÓMICAS PRINCIPALES ────────
// Catálogo resumido de actividades más frecuentes
export const ACTIVIDADES_ECONOMICAS: ActividadEconomica[] = [
  { codigo: '01111', descripcion: 'CULTIVO DE CEREALES (EXCEPTO ARROZ) Y OTROS CULTIVOS' },
  { codigo: '10101', descripcion: 'PROCESAMIENTO Y CONSERVACIÓN DE CARNE' },
  { codigo: '15201', descripcion: 'FABRICACIÓN DE CALZADO' },
  { codigo: '22110', descripcion: 'EDICIÓN DE LIBROS' },
  { codigo: '41001', descripcion: 'CONSTRUCCIÓN DE EDIFICIOS' },
  { codigo: '45100', descripcion: 'VENTA DE VEHÍCULOS AUTOMOTORES' },
  { codigo: '46100', descripcion: 'VENTA AL POR MAYOR A CAMBIO DE UNA RETRIBUCIÓN O CONTRATA' },
  { codigo: '46410', descripcion: 'VENTA AL POR MAYOR DE PRODUCTOS TEXTILES' },
  { codigo: '46491', descripcion: 'VENTA AL POR MAYOR DE OTROS ENSERES DOMÉSTICOS' },
  { codigo: '46900', descripcion: 'VENTA AL POR MAYOR NO ESPECIALIZADA' },
  { codigo: '47111', descripcion: 'VENTA AL POR MENOR EN ALMACENES NO ESPECIALIZADOS CON SURTIDO COMPUESTO PRINCIPALMENTE DE ALIMENTOS, BEBIDAS Y TABACO' },
  { codigo: '47190', descripcion: 'OTRAS ACTIVIDADES DE VENTA AL POR MENOR EN COMERCIOS NO ESPECIALIZADOS' },
  { codigo: '47410', descripcion: 'VENTA AL POR MENOR DE COMPUTADORAS Y PROGRAMAS INFORMÁTICOS' },
  { codigo: '47520', descripcion: 'VENTA AL POR MENOR DE MATERIALES DE CONSTRUCCIÓN' },
  { codigo: '47610', descripcion: 'VENTA AL POR MENOR DE LIBROS Y PERIÓDICOS' },
  { codigo: '47710', descripcion: 'VENTA AL POR MENOR DE PRENDAS DE VESTIR' },
  { codigo: '47730', descripcion: 'VENTA AL POR MENOR DE PRODUCTOS FARMACÉUTICOS' },
  { codigo: '47900', descripcion: 'OTRAS ACTIVIDADES DE VENTA AL POR MENOR NO REALIZADA EN COMERCIOS' },
  { codigo: '49100', descripcion: 'TRANSPORTE INTERURBANO DE PASAJEROS POR FERROCARRIL' },
  { codigo: '55101', descripcion: 'ACTIVIDADES DE ALOJAMIENTO TEMPORAL (HOTELES, MOTELES)' },
  { codigo: '56101', descripcion: 'RESTAURANTES Y SERVICIOS DE COMIDA' },
  { codigo: '56290', descripcion: 'OTRAS ACTIVIDADES DE SERVICIO DE COMIDAS' },
  { codigo: '58110', descripcion: 'EDICIÓN DE LIBROS' },
  { codigo: '61100', descripcion: 'ACTIVIDADES DE TELECOMUNICACIONES ALÁMBRICAS' },
  { codigo: '62010', descripcion: 'ACTIVIDADES DE PROGRAMACIÓN INFORMÁTICA' },
  { codigo: '62020', descripcion: 'CONSULTORÍA DE INFORMÁTICA Y GESTIÓN DE INSTALACIONES INFORMÁTICAS' },
  { codigo: '62090', descripcion: 'OTRAS ACTIVIDADES DE TECNOLOGÍA DE LA INFORMACIÓN Y SERVICIOS INFORMÁTICOS' },
  { codigo: '63110', descripcion: 'PROCESAMIENTO DE DATOS, HOSTING Y ACTIVIDADES CONEXAS' },
  { codigo: '64190', descripcion: 'OTROS TIPOS DE INTERMEDIACIÓN MONETARIA' },
  { codigo: '66300', descripcion: 'ACTIVIDADES DE ADMINISTRACIÓN DE FONDOS' },
  { codigo: '68100', descripcion: 'ACTIVIDADES INMOBILIARIAS CON BIENES PROPIOS O ARRENDADOS' },
  { codigo: '69100', descripcion: 'ACTIVIDADES JURÍDICAS' },
  { codigo: '69200', descripcion: 'ACTIVIDADES DE CONTABILIDAD, TENEDURÍA DE LIBROS Y AUDITORÍA' },
  { codigo: '70100', descripcion: 'ACTIVIDADES DE OFICINAS PRINCIPALES' },
  { codigo: '70200', descripcion: 'ACTIVIDADES DE CONSULTORÍA DE GESTIÓN' },
  { codigo: '71100', descripcion: 'ACTIVIDADES DE ARQUITECTURA E INGENIERÍA' },
  { codigo: '73110', descripcion: 'PUBLICIDAD' },
  { codigo: '74100', descripcion: 'ACTIVIDADES ESPECIALIZADAS DE DISEÑO' },
  { codigo: '74200', descripcion: 'ACTIVIDADES FOTOGRÁFICAS' },
  { codigo: '80100', descripcion: 'ACTIVIDADES DE SEGURIDAD PRIVADA' },
  { codigo: '82110', descripcion: 'ACTIVIDADES COMBINADAS DE SERVICIOS ADMINISTRATIVOS DE OFICINA' },
  { codigo: '85100', descripcion: 'ENSEÑANZA PREESCOLAR Y PRIMARIA' },
  { codigo: '85310', descripcion: 'ENSEÑANZA SECUNDARIA' },
  { codigo: '86100', descripcion: 'ACTIVIDADES DE HOSPITALES' },
  { codigo: '86210', descripcion: 'ACTIVIDADES DE MÉDICOS Y ODONTÓLOGOS' },
  { codigo: '86909', descripcion: 'OTRAS ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA' },
  { codigo: '93110', descripcion: 'GESTIÓN DE INSTALACIONES DEPORTIVAS' },
  { codigo: '96010', descripcion: 'LAVADO Y LIMPIEZA DE PRENDAS DE TELA Y DE PIEL' },
  { codigo: '96020', descripcion: 'PELUQUERÍA Y OTROS TRATAMIENTOS DE BELLEZA' },
  { codigo: '96090', descripcion: 'OTRAS ACTIVIDADES DE SERVICIOS PERSONALES N.C.P.' },
];
